### ISSUE TITLE
Use a common framework instead of laravel

### ISSUE THREAD

**Issue by dabeck** [rookian1337/plenty-fifa-liga#1]
.

**Comment by rookian1337** [comment]
geh bitte weiter :)

**Comment by dabeck** [comment]
🤔

**Comment by rookian1337** [comment]
http://www.sitepoint.com/best-php-framework-2015-sitepoint-survey-results/ ;)

**Comment by dabeck** [comment]
but PHP...

![php](http://tclhost.com/Pgp2UFT.gif)
